### ISSUE TITLE
Single thumb workaround ?

### ISSUE THREAD

**Issue by bakman2** [n3r4zzurr0/range-slider-input#6]
I want a slider with a single thumb as below ([inspired by daisy ui](https://daisyui.com/components/range/)). I styled the first thumb with the fore/background them same as the track. 

<img width="229" alt="image" src="https://user-images.githubusercontent.com/333960/209464114-d3016340-b98c-415d-bc4c-3b31e9674f75.png">

with ` thumbsDisabled: [true, false],`

I cannot hide the first thumb because the track will not render correctly
<img width="233" alt="image" src="https://user-images.githubusercontent.com/333960/209464128-1a50a0f9-28eb-4fae-84a4-70d0c960b2ca.png">

The problem with a disabled thumb is that one cannot click directly on the beginning (=0) of the track.
Is there a potential workaround ?

**Comment by n3r4zzurr0** [comment]
You can set the width of the first thumb to zero to hide it visually.
```css
.range-slider__thumb[data-lower] {
  width: 0;
}
```
And then to obtain a rounded corner on the left, modify the top-left and bottom-left border radius.
```css
/* 12px, if the height of the range is, let's say 24px, so 50% of it will give a circular arc */
.range-slider__range {
  border-top-left-radius: 12px;
  border-bottom-left-radius: 12px;
}
```

I have created a [codepen](https://codepen.io/n3r4zzurr0/pen/vYaNeJW) to demonstrate the same.
